# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('discipline', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('schedule', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='GradeVO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observation', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='StudentVO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField()),
                ('name', models.CharField(max_length=264)),
                ('class_scholl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.ClassVO')),
            ],
        ),
        migrations.AddField(
            model_name='gradevo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.StudentVO'),
        ),
        migrations.AddField(
            model_name='classvo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.CourseVO'),
        ),
    ]
