# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classvo',
            name='schedule',
            field=models.DateTimeField(verbose_name=['%H:%M']),
        ),
    ]
